import {
  Eye,
  Pencil,
  MenuSquare,
  Newspaper,
  Menu,
  User,
  X,
  Coins,
  Lock,
  Trash2,
  GripVertical,
  ArrowLeft,
  EyeOff,
  LogIn,
  CheckCheck,
  XCircle,
} from 'lucide-react';

export const iconsMap = {
  PasswordIcon: Eye,
  PasswordHideIcon: EyeOff,
  EditIcon: Pencil,
  BurgerIcon: MenuSquare,
  FeedIcon: Newspaper,
  MenuIcon: Menu,
  CloseIcon: X,
  ProfileIcon: User,
  LoginIcon: LogIn,
  PriceIcon: Coins,
  LockedIcon: Lock,
  RemoveIcon: Trash2,
  MoveIcon: GripVertical,
  BackIcon: ArrowLeft,
  TickIcon: CheckCheck,
  ErrorIcon: XCircle,
};
